trigger:
  batch: true
  paths:
    include:
      - templates/bicep/modules/*
  branches:
    include:
      - main
      - master

pool:
  vmImage: windows-latest

parameters:
- name: connectedServiceName
  type: string

- name: subscriptionId
  type: string

- name: acrName
  type: string

- name: acrResourceGroupName
  type: string

variables:
- name: devOpsOrganization
  value: $[replace(replace(variables['System.CollectionUri'], 'https://dev.azure.com/', ''), '/', '')]

- name: fileFilterPath
  value: /Templates/Bicep/modules/
  
steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - template: pipelines/steps/publishBicepModule.yaml
    parameters:
      devOpsOrganization: $(devOpsOrganization)
      devOpsProject: $(System.TeamProject)
      connectedServiceName: ${{ parameters.connectedServiceName }} 
      subscriptionId: ${{ parameters.subscriptionId }}
      acrName: ${{ parameters.acrName }}
      acrResourceGroupName: ${{ parameters.acrResourceGroupName }}
      repositoryName: $(Build.Repository.Name)
      fileFilterPath: $(fileFilterPath)